In [10]:
from __future__ import unicode_literals, print_function, division
from io import open
import unicodedata
import string
import re
import random

from os import listdir
from tqdm.notebook import tqdm
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F

from nltk.tokenize import word_tokenize


from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [11]:
unprocessed_file_name = 'unprocessed_file.pkl'
cleaned_file_name ='cleaned_file.pkl'
cnn = "/Users/rohankilledar/Documents/MSc Artificial Intelligence/repos/summarisation/cnn/stories"
path_of_downloaded_files = "/Users/rohankilledar/Documents/MSc Artificial Intelligence/repos/Natural Language Processing/glove.6B.50d.txt"
filename = "glove.6B.50d.txt"
embedding_dim = 50
data_size = 25000
hidden_size = 50

In [12]:
glove_file = datapath(path_of_downloaded_files)
word2vec_glove_file = get_tmpfile(filename)
glove2word2vec(glove_file, word2vec_glove_file)
word_vectors = KeyedVectors.load_word2vec_format(word2vec_glove_file)
print('loaded %s word vectors from %s.' % (len(word_vectors.key_to_index),filename ))

<ipython-input-12-0c6d93aa8805>:3: DeprecationWarning: Call to deprecated `glove2word2vec` (KeyedVectors.load_word2vec_format(.., binary=False, no_header=True) loads GLoVE text vectors.).
  glove2word2vec(glove_file, word2vec_glove_file)


In [ ]:
SOS_token = 0
EOS_token = 1

sos = 'sos'
eos = 'eos'



class Lang:
    def __init__(self, name):
        self.name = name
        self.words = []
        self.word2index = {}
        self.word2count = {}
        self.index2word = {}
        self.n_words = 0  # Count SOS and EOS
        self.glove = {}
        self.embedding_dim = word_vectors.get_vector('office').shape[0]

    def addSentence(self, sentence):
        for word in word_tokenize(sentence):
            self.addWord(word)

    def addWord(self, word):
        if word not in self.word2index:
            self.word2index[word] = self.n_words
            self.word2count[word] = 1
            self.index2word[self.n_words] = word
            self.n_words += 1
            self.words.append(word)
            if word not in self.glove:
                self.glove[word] = np.random.normal(scale=0.6 , size= (self.embedding_dim,))
        else:
            self.word2count[word] += 1

    def addPretrained(self,path_of_downloaded_files):
        with open(path_of_downloaded_files) as f:
            for indx,l in enumerate(f):
                line = l.split()
                word = line[0]
                if word == sos:
                    first_word = self.words[0]
                    self.words.append(first_word)
                    self.words[0] = sos
                    self.word2index[first_word] = indx
                    self.word2index[sos] = 0
                    self.index2word[indx] = first_word
                    self.index2word[0] = sos
                    self.glove[sos] = word_vectors[indx]
                    self.glove[first_word] = word_vectors[0]
                    self.word2count[sos] = 1
                    self.n_words += 1

                elif word == eos:
                    sec_word = self.words[1]
                    self.words.append(sec_word)
                    self.words[1] = eos
                    self.index2word[indx] = sec_word
                    self.index2word[1] = eos
                    self.word2index[sec_word] = indx
                    self.word2index[eos] = 1
                    self.glove[eos] = word_vectors[indx]
                    self.glove[sec_word] = word_vectors[1]
                    self.word2count[eos] = 1
                    self.n_words += 1
                else:
                    self.words.append(word)
                    self.word2count[word] = 1
                    self.word2index[word] = indx
                    self.index2word[indx]=word
                    self.glove[word] = word_vectors[indx]
                    self.n_words += 1
                    

In [ ]:
def decontracted(phrase): 
    phrase = re.sub(r"won't", "will not", phrase) 
    phrase = re.sub(r"can\'t", "can not", phrase)  
    phrase = re.sub(r"n\'t", " not", phrase)  
    phrase = re.sub(r"\'re", " are", phrase)  
    phrase = re.sub(r"\'s", " is", phrase)  
    phrase = re.sub(r"\'d", " would", phrase)  
    phrase = re.sub(r"\'ll", " will", phrase)  
    phrase = re.sub(r"\'t", " not", phrase)  
    phrase = re.sub(r"\'ve", " have", phrase)  
    phrase = re.sub(r"\'m", " am", phrase)  
    return phrase

In [ ]:
# Turn a Unicode string to plain ASCII, thanks to
# https://stackoverflow.com/a/518232/2809427
def unicodeToAscii(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn'
    )

# Lowercase, trim, and remove non-letter characters


def normalizeString(s):
    
    
    dash_indx = s.find('(CNN) --')
    if dash_indx>=0: #and dash_indx<=20:
        s = s[dash_indx+len('(CNN) --'):]
        
    s=decontracted(s)
    s = unicodeToAscii(s.lower().strip())

    s = re.sub(r"([.!?])", r" \1", s)
    s = re.sub(r"[^a-zA-Z.!?]+", r" ", s)
    return s

In [ ]:
def read_file(filename):
    file = open(filename, encoding= 'UTF-8')
    text = file.read()
    file.close()
    return text

def split_text(article):
    indx = article.index('@highlight')
    story = article[:indx]
    highlight = article[indx:].split('@highlight')

    highlight = ". ".join([h.strip() for h in highlight if len(h)>0])
    return story,highlight

In [ ]:
def read_all(folder):
    dataset = list()

    for file in tqdm(listdir(folder)):
        filename = folder + '/' + file
        article = read_file(filename)
        story,highlight = split_text(article)

        dataset.append({'story':story, 'highlight':highlight})
    
    return dataset

dataset = read_all(cnn)

  0%|          | 0/92579 [00:00<?, ?it/s]

In [ ]:
#saving dataset for cleaning
import pickle
output_file = open(unprocessed_file_name,'wb')
pickle.dump(dataset, output_file)
output_file.close()

In [ ]:

dataset = pd.read_pickle(unprocessed_file_name)
#reducing the dataset for initial testing of model
dataset = dataset[:data_size]

In [ ]:
df = pd.DataFrame(dataset)

In [ ]:
df['story'] = df['story'].apply(lambda x: normalizeString(x))
df['highlight'] = df['highlight'].apply(lambda x: normalizeString(x))

In [ ]:
df['highlight'] = df['highlight'].apply(lambda x: sos + " " + x )

In [ ]:
df['word_count_text'] = df['story'].apply(lambda x: len(str(x).split()))
df['highlight_count'] = df['highlight'].apply(lambda x: len(str(x).split()))
from math import floor
print("The mean word count length of text article is " + str(floor(df['word_count_text'].mean())))
print("The mean word count length of summary/highlight is " + str(floor(df['highlight_count'].mean())))

max_article_len = floor(df['word_count_text'].max())
max_summary_len = floor(df['highlight_count'].max())
print("The max word count length of text article is " + str(max_article_len))
print("The max word count length of summary/highlight is " + str(max_summary_len))

The mean word count length of text article is 689
The mean word count length of summary/highlight is 46
The max word count length of text article is 1884
The max word count length of summary/highlight is 82


In [ ]:
df.drop('word_count_text', axis=1, inplace=True)
df.drop('highlight_count', axis=1, inplace=True)

In [ ]:
vocab = Lang('vocab')
vocab.addPretrained(path_of_downloaded_files)
def prepareData():
    for indx,row in tqdm(df.iterrows()):
        vocab.addSentence(row['story'])
        vocab.addSentence(row['highlight'])
    print("counted Words:")
    print(vocab.name, vocab.n_words)
prepareData()

0it [00:00, ?it/s]

counted Words:
vocab 402650


In [ ]:
pairs = df.values.tolist()

In [ ]:
def indexesFromSentence(lang, sentence):
    # return [lang.word2index[word] for word in sentence.split(' ')]
    return [lang.word2index[word] for word in word_tokenize(sentence)]


def tensorFromSentence(lang, sentence):
    indexes = indexesFromSentence(lang, sentence)
    indexes.append(EOS_token)
    return torch.tensor(indexes, dtype=torch.long, device=device).view(-1, 1)


def tensorsFromPair(pair):
    input_tensor = tensorFromSentence(vocab, pair[0])
    target_tensor = tensorFromSentence(vocab, pair[1])
    return (input_tensor, target_tensor)

In [ ]:

def generate_weights(unique_word_corpus,glove, tens=True):
    matrix_len = len(unique_word_corpus)
    unique_word2indx = {}
    
    weight_matrix  = np.zeros((matrix_len, embedding_dim))
   
    words_found = 0

    for indx, word in enumerate(unique_word_corpus):
        try:
            unique_word2indx[word] = indx
            weight_matrix[indx] = glove[word]
            words_found +=1
        except KeyError:
            weight_matrix[indx] = np.random.normal(scale=0.6 , size= (embedding_dim,))
            unique_word2indx[word] = indx
    if tens:
        return torch.from_numpy(weight_matrix) , unique_word2indx
    else:
        return weight_matrix,unique_word2indx

weight_matrix, meh= generate_weights(vocab.words, vocab.glove)

In [ ]:
weight_matrix

tensor([[ 0.5139, -0.7162, -0.2702,  ...,  0.1683,  0.5761,  0.0467],
        [-0.3090,  0.1448,  1.1682,  ..., -0.4097, -0.4651, -0.2958],
        [ 0.1516,  0.3018, -0.1676,  ..., -0.3565,  0.0164,  0.1022],
        ...,
        [ 0.6183, -0.7022, -0.0809,  ...,  0.2502,  0.2620,  0.2695],
        [ 1.3004, -0.1501,  0.6362,  ..., -0.0593, -0.4022, -0.8937],
        [-0.0462, -0.2653,  0.0253,  ...,  0.0821,  0.0608, -0.4605]],
       dtype=torch.float64)

In [ ]:
vocab.glove['sos']

array([ 0.51387 , -0.71619 , -0.27022 , -0.39605 ,  0.077725, -0.51019 ,
       -0.096037, -0.51926 ,  1.1398  , -0.48839 ,  0.55519 , -0.079659,
        0.63065 , -0.19989 , -0.72763 , -1.1698  , -0.78838 , -0.11933 ,
       -0.016341,  0.58433 , -0.60493 ,  0.34394 , -0.10728 ,  0.38154 ,
        0.60439 ,  0.098549, -0.62968 , -0.55329 , -0.40243 , -0.75822 ,
        0.58165 ,  0.8636  , -0.80085 ,  0.26178 , -1.1834  ,  0.099697,
        0.56937 , -1.6251  ,  0.4834  ,  0.36138 ,  0.73861 , -0.65523 ,
       -0.31002 , -0.65169 ,  0.51786 ,  0.39711 ,  0.22438 ,  0.16832 ,
        0.57609 ,  0.046694], dtype=float32)

In [ ]:
word = 'the'
embeds = nn.Embedding(vocab.n_words, embedding_dim)  # 2 words in vocab, 5 dimensional embeddings
embeds =embeds.from_pretrained(weight_matrix)
lookup_tensor = torch.tensor([vocab.word2index[word]], dtype=torch.long)
print(vocab.word2index[word])
print(lookup_tensor)
hello_embed = embeds(lookup_tensor)
print(hello_embed)
print(weight_matrix[vocab.word2index[word]])


28069
tensor([28069])
tensor([[ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
         -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
          2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
          1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
         -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
         -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
          4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
          7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
         -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
          1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01]],
       dtype=torch.float64)
tensor([ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
        -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
         2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9

In [ ]:
x = torch.rand(2,2,2)
print(type(x))
print(x.dtype)
double_x = x.double()
print(type(double_x))
print(double_x.dtype)

<class 'torch.Tensor'>
torch.float32
<class 'torch.Tensor'>
torch.float64


In [ ]:
class EncoderRNN(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(EncoderRNN, self).__init__()
        self.hidden_size = hidden_size
       # self.num_layers = num_layers
        self.embedding = nn.Embedding(vocab.n_words, embedding_dim)
        self.embedding = self.embedding.from_pretrained(weight_matrix)
        #self.embedding.from_pretrained(glove)
        self.lstm = nn.LSTM(hidden_dim, hidden_dim)
        #self.dropout = nn.Dropout(dropout)

    def forward(self, input, hidden):

        embedded = self.embedding(input).view(1, 1, -1)
        output = embedded
       # print(output)
        #print(hidden)
        output, hidden = self.lstm(output.float(), hidden)
        return output, hidden

    def initHidden(self):
        #in case of LSTM we need h0 and c0 hence init this as a tuple (h0,c0) and passed as hidden to lstm and in case of gru its just h0
       return (torch.zeros(1, 1, self.hidden_size, dtype=torch.float32, device=device), torch.zeros(1,1,self.hidden_size,dtype = torch.float32, device= device))

In [ ]:
class DecoderRNN(nn.Module):
    def __init__(self, hidden_size, output_size):
        super(DecoderRNN, self).__init__()
        self.hidden_size = hidden_size

        self.embedding = nn.Embedding(output_size, hidden_size)
        self.embedding.from_pretrained(weight_matrix)
        self.lstm = nn.LSTM(hidden_size, hidden_size)
        #self.out = nn.Linear(hidden_size, output_size)
        self.softmax = nn.LogSoftmax(dim=1)

    def forward(self, input, hidden):
        output = self.embedding(input).view(1, 1, -1)
        output = F.relu(output)
        output, hidden = self.lstm(output, hidden)
        #output = self.softmax(self.out(output[0]))
        output = self.softmax(output[0])
        return output, hidden

    def initHidden(self):
        return (torch.zeros(1, 1, self.hidden_size, dtype = 'float32', device=device), torch.zeros(1,1,self.hidden_size,dtype = 'float32', device= device))

In [ ]:
class AttnDecoderRNN(nn.Module):
    def __init__(self, hidden_size, output_size, dropout_p=0.1, max_length=max_article_len):
        super(AttnDecoderRNN, self).__init__()
        
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.dropout_p = dropout_p
        self.max_length = max_length

        self.embedding = nn.Embedding(self.output_size, self.hidden_size)
        self.attn = nn.Linear(self.hidden_size * 2, self.max_length)
        self.attn_combine = nn.Linear(self.hidden_size * 2, self.hidden_size)
        self.dropout = nn.Dropout(self.dropout_p)
        self.lstm = nn.LSTM(self.hidden_size, self.hidden_size)
        self.out = nn.Linear(self.hidden_size, self.output_size)

    def forward(self, input, hidden, encoder_outputs):
        
        embedded = self.embedding(input).view(1, 1, -1)
        embedded = self.dropout(embedded)
       
        #print(embedded[0].shape)
        
        attn_weights = F.softmax(
            self.attn(torch.cat((embedded, hidden[0]), 1)), dim=1)
        attn_applied = torch.bmm(attn_weights.unsqueeze(0),
                                 encoder_outputs.unsqueeze(0))

                                 

        output = torch.cat((embedded[0], attn_applied[0]), 1)
        output = self.attn_combine(output).unsqueeze(0)

        output = F.relu(output)
        output, hidden = self.lstm(output, hidden)

        output = F.log_softmax(self.out(output[0]), dim=1)
        return output, hidden, attn_weights

    def initHidden(self):
       return (torch.zeros(1, 1, self.hidden_size, dtype=torch.int64, device=device), torch.zeros(1,1,self.hidden_size,dtype = torch.int64, device= device))

In [ ]:
# from nltk.tokenize import word_tokenize

# def indexesFromSentence(lang, sentence):
#     #return [lang.glove[word] for word in sentence.split(' ')]
#     return [lang.word2index[word] for word in word_tokenize(sentence)]
#     #return [lang.word2index[word] for word in sentence.split(' ')]
# def tensorFromSentence(lang, sentence):
#     indexes = indexesFromSentence(lang, sentence)
#     indexes.append(EOS_token)
#     # indexes.append(lang.glove[eos])
#     #change it to include glove values
#     #return indexes
#     return torch.Tensor(indexes,dtype=torch.long).view(-1, 1)


# def tensorsFromPair(pair):
#     input_tensor = tensorFromSentence(vocab, pair[0])
#     target_tensor = tensorFromSentence(vocab, pair[1])
#     return (input_tensor, target_tensor)

In [ ]:
import matplotlib.pyplot as plt
plt.switch_backend('agg')
import matplotlib.ticker as ticker
import numpy as np


def showPlot(points):
    plt.figure()
    fig, ax = plt.subplots()
    # this locator puts ticks at regular intervals
    loc = ticker.MultipleLocator(base=0.2)
    ax.yaxis.set_major_locator(loc)
    plt.plot(points)

In [ ]:
teacher_forcing_ratio = 0.5


def train(input_tensor, target_tensor, encoder, decoder, encoder_optimizer, decoder_optimizer, criterion, attn, max_length=vocab.n_words):
    encoder_hidden = encoder.initHidden()

    encoder_optimizer.zero_grad()
    decoder_optimizer.zero_grad()

    input_length = input_tensor.size(0)
    target_length = target_tensor.size(0)

    encoder_outputs = torch.zeros(max_length, encoder.hidden_size, device=device)

    loss = 0

    for ei in range(input_length):
        encoder_output, encoder_hidden = encoder(
            input_tensor[ei], encoder_hidden)
        encoder_outputs[ei] = encoder_output[0, 0]

    decoder_input = torch.tensor([[SOS_token]], device=device)

    decoder_hidden = encoder_hidden

    use_teacher_forcing = True if random.random() < teacher_forcing_ratio else False

    if use_teacher_forcing:
        # Teacher forcing: Feed the target as the next input
        for di in range(target_length):
            if attn :
                decoder_output, decoder_hidden, decoder_attention = decoder(
                    decoder_input, decoder_hidden, encoder_outputs)
            else:
                decoder_output, decoder_hidden= decoder(
                    decoder_input, decoder_hidden)
                tar_tens = weight_matrix[target_tensor[di].item()].view(-1).float()
            loss += criterion(decoder_output.view(-1), tar_tens)
            decoder_input = target_tensor[di]  # Teacher forcing

    else:
        # Without teacher forcing: use its own predictions as the next input
        for di in range(target_length):
            if attn :
                decoder_output, decoder_hidden, decoder_attention = decoder(
                    decoder_input, decoder_hidden, encoder_outputs)
            else:
                decoder_output, decoder_hidden= decoder(
                    decoder_input, decoder_hidden)
            topv, topi = decoder_output.topk(1)
            decoder_input = topi.squeeze().detach()  # detach from history as input

            tar_tens = weight_matrix[target_tensor[di].item()].view(-1).float()
            loss += criterion(decoder_output.view(-1), tar_tens)
            if decoder_input.item() == EOS_token:
                break

    loss.backward()

    encoder_optimizer.step()
    decoder_optimizer.step()

    return loss.item() / target_length

In [ ]:
import time
import math


def asMinutes(s):
    m = math.floor(s / 60)
    s -= m * 60
    return '%dm %ds' % (m, s)


def timeSince(since, percent):
    now = time.time()
    s = now - since
    es = s / (percent)
    rs = es - s
    return '%s (- %s)' % (asMinutes(s), asMinutes(rs))

In [ ]:
def trainIters(encoder, decoder, n_iters, attn=True, print_every=1000, plot_every=100, learning_rate=0.01):
    start = time.time()
    print(start)

    plot_losses = []
    print_loss_total = 0  # Reset every print_every
    plot_loss_total = 0  # Reset every plot_every
    print('encoder optimizer init')
    encoder_optimizer = optim.SGD(encoder.parameters(), lr=learning_rate)
    print('decoder optimizer init')
    decoder_optimizer = optim.SGD(decoder.parameters(), lr=learning_rate)
    
    print('choosing training pairs:' + str(n_iters))
    training_pairs = [tensorsFromPair(random.choice(pairs))
                      for i in range(n_iters)]
    
    print('init criterion')
    # criterion = nn.NLLLoss()
    criterion = nn.MSELoss()
    
    print('starting iterations')
    
    for iter in tqdm(range(1, n_iters + 1)):
        training_pair = training_pairs[iter - 1]
        input_tensor = training_pair[0]
        target_tensor = training_pair[1]

        loss = train(input_tensor, target_tensor, encoder,
                     decoder, encoder_optimizer, decoder_optimizer, criterion, attn)
        
        print_loss_total += loss
        plot_loss_total += loss

        if iter % print_every == 0:
            print_loss_avg = print_loss_total / print_every
            print_loss_total = 0
            print('%s (%d %d%%) %.4f' % (timeSince(start, iter / n_iters),
                                         iter, iter / n_iters * 100, print_loss_avg))

        if iter % plot_every == 0:
            plot_loss_avg = plot_loss_total / plot_every
            plot_losses.append(plot_loss_avg)
            plot_loss_total = 0

    showPlot(plot_losses)

In [ ]:
training_pairs = [tensorsFromPair(random.choice(pairs))
                     for i in range(3)]

In [ ]:
par = training_pairs[1][1]


In [ ]:
tpair = training_pairs[0]
inp = tpair[0]
tar = tpair[1]
inp_size = inp.size(0)
tar_size = tar.size(0)
hidden_dim = 50
# print(tar_size)

# print(inp[0])

# print(vocab.n_words)

encoder = EncoderRNN(vocab.n_words,50)
encoder_hidden = encoder.initHidden()
encoder_outputs = torch.zeros(inp_size,hidden_size, device=device)


for i in range(inp_size):
   
    encoder_output, encoder_hidden = encoder(inp[i], encoder_hidden)

    encoder_outputs[i] = encoder_output[0, 0]

#print(encoder_outputs.shape)

decoder_input = torch.tensor([[SOS_token]], device=device)

#print(decoder_input)
decoder_hidden = encoder_hidden

decoder = DecoderRNN(hidden_size,vocab.n_words)
loss  = 0
# criterion = nn.NLLLoss()
criterion = nn.MSELoss()

for i in range(tar_size):
    decoder_output, decoder_hidden= decoder(decoder_input, decoder_hidden)
    
    # print(decoder_output.view(-1).shape)
    # print(tar[i].shape)
    # print(weight_matrix[tar[i].item()].view(-1).shape)
    tar_tens = weight_matrix[tar[i].item()].view(-1).float()
    # print(tar_tens.type())
    # print(decoder_output.type())
    # print(tar_tens)
    # print(decoder_output)
    topv, topi = decoder_output.data.topk(1)
    print(vocab.index2word[topi.item()])
    loss += criterion(decoder_output.view(-1),tar_tens )
    
    decoder_input = tar[i]  # Teacher forcing


an
``
and
and
``
he
``
-
``
at
-
-
``
he
-
-
to
he
-
will
he
he
-
-
``
-
``
-
``
``
``
he
he
which
``
will
``
he


In [ ]:

word_indx = inp[1].item()
word = vocab.index2word[word_indx]
print(word)
print(vocab.glove[word])
print(weight_matrix[word_indx])


hidden = (torch.zeros(1, 1, 50),torch.zeros(1, 1, 50))
print(hidden[0].shape)
print(len(vocab.words))
embedded = nn.Embedding(len(vocab.words),50)
lstm = nn.LSTM(50,50)
embedded.from_pretrained(weight_matrix)
#lin = nn.Linear(hidden_size, tar_size)
softmax = nn.LogSoftmax(dim=1)

print(inp[1].item())
print(weight_matrix[inp[1].item()].view(-1))
print(vocab.index2word[inp[1].item()])
#print(vocab.glove['the'])
out = embedded(inp[1]).view(1,1,-1)
print(out)
print(out.shape)
out = F.relu(out)
output, hidden = lstm(out, hidden)
print(output.shape)
#output = softmax(output[0])
print(output.view(-1))



# out = embedded(inp[1]).view(1,1,-1)
# output, hidden = lstm(out, hidden)


#print(output.shape)

henson
[ 0.28302   -0.98354   -0.47318    0.97362    0.65512    0.65159
 -1.2712    -0.45614    0.28934    0.10817   -0.096854   1.2445
 -0.16026    0.077745   0.56126    0.072962   0.26976    0.29677
 -0.70432   -0.10092    0.10159    0.76659   -0.29101   -0.38968
  0.61176    0.48632    0.74082   -0.39317   -0.56144   -1.1879
 -0.0040155 -0.24041    0.60474   -0.23765    0.012554   0.5866
  0.22144   -0.67394    0.35473   -0.81246   -0.43274    0.1196
 -1.1431     0.03929   -0.057025   0.87628   -0.10193   -0.57598
 -0.42348    0.28004  ]
tensor([ 0.2830, -0.9835, -0.4732,  0.9736,  0.6551,  0.6516, -1.2712, -0.4561,
         0.2893,  0.1082, -0.0969,  1.2445, -0.1603,  0.0777,  0.5613,  0.0730,
         0.2698,  0.2968, -0.7043, -0.1009,  0.1016,  0.7666, -0.2910, -0.3897,
         0.6118,  0.4863,  0.7408, -0.3932, -0.5614, -1.1879, -0.0040, -0.2404,
         0.6047, -0.2377,  0.0126,  0.5866,  0.2214, -0.6739,  0.3547, -0.8125,
        -0.4327,  0.1196, -1.1431,  0.0393, -0.0570, 

In [ ]:
def evaluate(encoder, decoder, sentence ,max_length=vocab.n_words, attn=True): # please check what should be max_length
    with torch.no_grad():
        input_tensor = tensorFromSentence(vocab, sentence)
        input_length = input_tensor.size()[0]
        encoder_hidden = encoder.initHidden()

        encoder_outputs = torch.zeros(max_length, encoder.hidden_size, device=device)

        for ei in range(input_length):
            encoder_output, encoder_hidden = encoder(input_tensor[ei],
                                                     encoder_hidden)
            encoder_outputs[ei] += encoder_output[0, 0]

        decoder_input = torch.tensor([[SOS_token]], device=device)  # SOS

        decoder_hidden = encoder_hidden

        decoded_words = []
        decoder_attentions = torch.zeros(max_length, max_length)

        for di in range(max_length):
            if attn:
                decoder_output, decoder_hidden, decoder_attention = decoder(
                    decoder_input, decoder_hidden, encoder_outputs)
                decoder_attentions[di] = decoder_attention.data
            else:
                decoder_output, decoder_hidden = decoder(
                    decoder_input, decoder_hidden) 
            topv, topi = decoder_output.data.topk(1)
            if topi.item() == EOS_token:
                decoded_words.append('<EOS>')
                break
            else:
                decoded_words.append(vocab.index2word[topi.item()])

            decoder_input = topi.squeeze().detach()

        return decoded_words, decoder_attentions[:di + 1]

In [ ]:
def evaluateRandomly(encoder, decoder, n=10):
    for i in range(n):
        pair = random.choice(pairs)
        print('>', pair[0])
        print('=', pair[1])
        output_words, attentions = evaluate(encoder, decoder, pair[0],attn=False)
        output_sentence = ' '.join(output_words)
        print('<', output_sentence)
        print('')

In [ ]:
hidden_size = 50
voc_size = len(vocab.words)
hidden_dim = 50
max_summary_size = 60
encoder1 = EncoderRNN(vocab.n_words, hidden_size).to(device)
decoder1 = DecoderRNN(hidden_size, vocab.n_words).to(device)
#attn_decoder1 = AttnDecoderRNN(hidden_size, vocab.n_words, dropout_p=0.1).to(device)



NameError: name 'vocab' is not defined

In [ ]:
#trainIters(encoder1, attn_decoder1, 4000, print_every=500)

trainIters(encoder1, decoder1,20000,False, print_every=1000)

1638058551.026687
encoder optimizer init
decoder optimizer init
choosing training pairs:1000
init criterion
starting iterations


  0%|          | 0/1000 [00:00<?, ?it/s]

0m 59s (- 18m 41s) (50 5%) 15.8081
1m 48s (- 16m 16s) (100 10%) 15.8344
2m 42s (- 15m 20s) (150 15%) 15.8172
3m 34s (- 14m 19s) (200 20%) 15.8584
4m 26s (- 13m 18s) (250 25%) 15.8079
5m 13s (- 12m 11s) (300 30%) 15.7736
6m 3s (- 11m 15s) (350 35%) 15.8388
7m 0s (- 10m 31s) (400 40%) 15.8239
8m 8s (- 9m 57s) (450 45%) 15.8137
9m 17s (- 9m 17s) (500 50%) 15.8387
10m 17s (- 8m 25s) (550 55%) 15.8460
11m 19s (- 7m 32s) (600 60%) 15.8141
12m 20s (- 6m 38s) (650 65%) 15.8584
13m 19s (- 5m 42s) (700 70%) 15.8271
14m 21s (- 4m 47s) (750 75%) 15.7761
15m 29s (- 3m 52s) (800 80%) 15.8048
16m 36s (- 2m 55s) (850 85%) 15.8359
17m 48s (- 1m 58s) (900 90%) 15.8265
18m 47s (- 0m 59s) (950 95%) 15.7865
19m 55s (- 0m 0s) (1000 100%) 15.8070


In [ ]:
import pickle

# save model and other necessary modules
all_info_want_to_save = {
    'encoder': encoder1,
    'decoder': decoder1
}

with open("enc_dec.pkl","wb") as save_path:
    pickle.dump(all_info_want_to_save, save_path)




In [ ]:
evaluateRandomly(encoder1, decoder1)

NameError: name 'encoder1' is not defined